"use client";
import Link from "next/link";
import { ArrowLeft, Calculator, ExternalLink, GraduationCap, SearchCheck } from "lucide-react";
import { useMemo, useState } from "react";

export default function UpuPage(){
 const [pngk,setPNGK]=useState("3.00"); const [coco,setCoco]=useState("8.00"); const [programMerit,setProgramMerit]=useState("");
 const result=useMemo(()=>{const p=Math.min(4,Math.max(0,Number(pngk)||0));const c=Math.min(10,Math.max(0,Number(coco)||0));const total=(p/4)*90+c;const benchmark=programMerit===""?null:Math.min(100,Math.max(0,Number(programMerit)||0));return {academic:(p/4)*90,total,benchmark,difference:benchmark===null?null:total-benchmark}},[pngk,coco,programMerit]);
 return <main className="simple-page"><div className="simple-shell wide"><Link className="back-link" href="/"><ArrowLeft/> Kembali ke portal</Link><header><GraduationCap/><small>HALA TUJU SELEPAS STPM</small><h1>Hala Tuju UPU</h1><p>Semak urusan UPU, kira merit dan cari program pengajian daripada sumber rasmi.</p></header>
 <div className="upu-grid"><section className="merit-card"><div className="module-heading"><Calculator/><div><small>KALKULATOR MERIT STPM</small><h2>Kira dan banding merit</h2></div></div><div className="merit-inputs"><label>PNGK STPM<input type="number" min="0" max="4" step="0.01" value={pngk} onChange={e=>setPNGK(e.target.value)}/></label><label>Markah kokurikulum<input type="number" min="0" max="10" step="0.01" value={coco} onChange={e=>setCoco(e.target.value)}/></label><label>Purata merit program (%)<input type="number" min="0" max="100" step="0.01" placeholder="Rujuk e-Panduan" value={programMerit} onChange={e=>setProgramMerit(e.target.value)}/></label></div><div className="merit-result"><span>Akademik (90%)<strong>{result.academic.toFixed(2)}</strong></span><span>Jumlah merit<strong>{result.total.toFixed(2)}%</strong></span></div>{result.difference!==null&&<div className={`merit-comparison ${result.difference>=0?"above":"below"}`}><strong>{result.difference>=0?"Lebih kompetitif berdasarkan angka rujukan":"Persaingan mungkin lebih tinggi"}</strong><span>Perbezaan {result.difference>=0?"+":""}{result.difference.toFixed(2)} mata daripada purata merit program {result.benchmark!.toFixed(2)}%.</span></div>}<p>Formula: (PNGK ÷ 4.00 × 90) + markah kokurikulum. Purata merit ialah rujukan persaingan, bukan jaminan tawaran.</p></section>
 <aside className="upu-actions"><a href="https://upu.mohe.gov.my/" target="_blank" rel="noopener noreferrer"><GraduationCap/><span><strong>Semakan UPU</strong><small>Buka laman rasmi permohonan, keputusan dan rayuan.</small></span><ExternalLink/></a><a href="https://online.mohe.gov.my/epanduan/" target="_blank" rel="noopener noreferrer"><SearchCheck/><span><strong>Carian Program</strong><small>Semak program, universiti dan syarat khas.</small></span><ExternalLink/></a><a href="https://online.mohe.gov.my/epanduan/kalkulatorMerit/stpm" target="_blank" rel="noopener noreferrer"><Calculator/><span><strong>Semak Kalkulator Rasmi</strong><small>Bandingkan kiraan dengan kalkulator UPU.</small></span><ExternalLink/></a></aside></div>
 <section className="upu-help"><h2>Aliran yang lebih mudah untuk pelajar</h2><div><span><b>1</b><strong>Kira merit</strong><small>Gunakan PNGK dan markah kokurikulum.</small></span><span><b>2</b><strong>Cari program</strong><small>Semak syarat am dan syarat khas.</small></span><span><b>3</b><strong>Susun pilihan</strong><small>Utamakan program yang diminati dan layak.</small></span></div></section><p className="page-note">Maklumat tawaran dan keputusan rasmi adalah tertakluk kepada BKPA, JPT dan universiti awam.</p></div></main>
}
