"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Inbox, LogOut, MessageSquareReply, RefreshCw, Send } from "lucide-react";

type Conversation = { id:number; referenceCode:string; topic:string; displayName:string|null; contactNumber:string|null; assignedTo:string|null; status:string; createdAt:string; updatedAt:string };
type Detail = { conversation:Conversation; messages:Array<{id:number;sender:string;body:string;createdAt:string}> };
export default function CounselorDashboard({email,role}:{email:string;role:string}) {
 const [items,setItems]=useState<Conversation[]>([]); const [selected,setSelected]=useState<Detail|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function loadList(){setBusy(true);const r=await fetch("/api/kaunselor",{cache:"no-store"});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setItems(d.conversations)}
 async function open(reference:string){setBusy(true);const r=await fetch(`/api/kaunselor?reference=${encodeURIComponent(reference)}`,{cache:"no-store"});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setSelected(d)}
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);const f=new FormData(e.currentTarget);const r=await fetch("/api/kaunselor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reference:selected.conversation.referenceCode,message:f.get("message")})});setBusy(false);if(!r.ok)return setError((await r.json()).error);e.currentTarget.reset();await open(selected.conversation.referenceCode);await loadList()}
 async function finish(){if(!selected)return;await fetch("/api/kaunselor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reference:selected.conversation.referenceCode,status:"selesai"})});await open(selected.conversation.referenceCode);await loadList()}
 useEffect(()=>{loadList();const timer=setInterval(loadList,60000);return()=>clearInterval(timer)},[]);
 return <main className="dashboard-page"><header className="dashboard-top"><div><Link href="/"><ArrowLeft/> Portal</Link><h1>{role==="admin"?"Dashboard Pentadbir":"Dashboard Kaunselor"}</h1><p>{email} · {role==="admin"?"Pentadbir Portal":"Kaunselor"}</p></div><div><button onClick={loadList}><RefreshCw/> Muat semula</button><a href="/cdn-cgi/access/logout"><LogOut/> Log keluar</a></div></header><div className="dashboard-layout"><aside><div className="inbox-title"><Inbox/><strong>Mesej pelajar</strong><span>{items.filter(i=>i.status==="baharu").length} baharu</span></div>{error&&<p className="form-error">{error}</p>}<div className="conversation-list">{items.map(i=><button key={i.id} className={selected?.conversation.id===i.id?"active":""} onClick={()=>open(i.referenceCode)}><span><strong>{i.topic}</strong><small>{i.referenceCode} · {i.displayName||"Tanpa nama"}</small></span><em className={i.status}>{i.status}</em></button>)}{!busy&&items.length===0&&<p>Belum ada mesej.</p>}</div></aside><section className="dashboard-thread">{!selected?<div className="empty-thread"><MessageSquareReply/><h2>Pilih mesej untuk dibaca</h2><p>{role==="admin"?"Akses pentadbir adalah untuk pemantauan dan pengurusan portal.":"Mesej baharu akan muncul di sebelah kiri."}</p></div>:<><header><div><small>{selected.conversation.referenceCode}</small><h2>{selected.conversation.topic}</h2><p>{selected.conversation.displayName||"Tanpa nama"}{selected.conversation.contactNumber?` · ${selected.conversation.contactNumber}`:""}</p></div><button onClick={finish}>Tandakan selesai</button></header><div className="message-list">{selected.messages.map(m=><div key={m.id} className={`message-bubble ${m.sender}`}><small>{m.sender==="kaunselor"?"Kaunselor":"Pelajar"}</small><p>{m.body}</p></div>)}</div>{role==="kaunselor"?<form onSubmit={send}><textarea name="message" required rows={4} placeholder="Tulis jawapan kepada pelajar..."/><button disabled={busy}><Send/> Hantar jawapan</button></form>:<p className="admin-notice">Pentadbir boleh memantau dan mengurus status. Jawapan kepada pelajar dihantar oleh kaunselor.</p>}</>}</section></div></main>
}
